package probandohibernateluis;
// Generated 25-ene-2019 13:47:57 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personas generated by hbm2java
 */
@Entity
@Table(name="Personas"
    ,schema="dbo"
    ,catalog="probandoHibernate"
)
public class Personas  implements java.io.Serializable {

    @Id 
    @Column(name="IDPersona", unique=true, nullable=false)
    @GeneratedValue
     private int idpersona;
    
    @Column(name="nombrePersona", length=30)
     private String nombrePersona;
    
    @Column(name="apellidosPersona", length=30)
     private String apellidosPersona;
    
    @Temporal(TemporalType.DATE)
    @Column(name="fechaNacimiento", length=10)
     private Date fechaNacimiento;
    
    @Column(name="telefono", length=12)
     private String telefono;
    
    @Column(name="direccion", length=50)
     private String direccion;
    
    @Column(name="IDDepartamento")
     private Integer iddepartamento;

    public Personas() {
    }

	
    public Personas(int idpersona) {
        this.idpersona = idpersona;
    }
    public Personas(String nombrePersona, String apellidosPersona, Date fechaNacimiento, String telefono, String direccion, Integer iddepartamento) {
       this.nombrePersona = nombrePersona;
       this.apellidosPersona = apellidosPersona;
       this.fechaNacimiento = fechaNacimiento;
       this.telefono = telefono;
       this.direccion = direccion;
       this.iddepartamento = iddepartamento;
    }
   
    public int getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(int idpersona) {
        this.idpersona = idpersona;
    }

    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }

    public String getApellidosPersona() {
        return this.apellidosPersona;
    }
    
    public void setApellidosPersona(String apellidosPersona) {
        this.apellidosPersona = apellidosPersona;
    }

    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public Integer getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(Integer iddepartamento) {
        this.iddepartamento = iddepartamento;
    }




}


